const countries = [
  {
    image: "./img/germany.png",
    name: "Germany",
    population: 81770900,
    region: "Europe",
    sub_region: "Western Europe",
    capital: "Berlin",
    domain: ".de",
    currency: "Euro",
    languages: ["German"],
    borders: ["France", "Netherlands", "Belgium"],
  },
  {
    image: "./img/usa.png",
    name: "United States of America",
    population: 323947000,
    region: "Americas",
    sub_region: "North America",
    capital: "Washington, D.C.",
    domain: ".us",
    currency: "US Dollar",
    languages: ["English"],
    borders: ["Canada", "Mexico"],
  },
  {
    image: "./img/brazil.png",
    name: "Brazil",
    population: 206135893,
    region: "Americas",
    sub_region: "South America",
    capital: "Brasilia",
    domain: ".br",
    currency: "Brazilian Real",
    languages: ["Portuguese"],
    borders: ["Argentina", "Colombia", "Peru"],
  },
  {
    image: "./img/iceland.png",
    name: "Iceland",
    population: 334300,
    region: "Europe",
    sub_region: "Northern Europe",
    capital: "Reykjavik",
    domain: ".is",
    currency: "Icelandic Króna",
    languages: ["Icelandic"],
    borders: [],
  },
  {
    image: "./img/afghanistan.png",
    name: "Afghanistan",
    population: 27657145,
    region: "Asia",
    sub_region: "Southern Asia",
    capital: "Kabul",
    domain: ".af",
    currency: "Afghan Afghani",
    languages: ["Pashto", "Dari"],
    borders: ["Pakistan", "Iran", "Uzbekistan"],
  },
  {
    image: "./img/aland.png",
    name: "Åland Islands",
    population: 28875,
    region: "Europe",
    sub_region: "Northern Europe",
    capital: "Mariehamn",
    domain: ".ax",
    currency: "Euro",
    languages: ["Swedish"],
    borders: [],
  },
  {
    image: "./img/albania.png",
    name: "Albania",
    population: 2886026,
    region: "Europe",
    sub_region: "Southern Europe",
    capital: "Tirana",
    domain: ".al",
    currency: "Albanian Lek",
    languages: ["Albanian"],
    borders: ["Greece", "Montenegro", "Kosovo"],
  },
  {
    image: "./img/algeria.png",
    name: "Algeria",
    population: 40400000,
    region: "Africa",
    sub_region: "Northern Africa",
    capital: "Algiers",
    domain: ".dz",
    currency: "Algerian Dinar",
    languages: ["Arabic"],
    borders: ["Tunisia", "Libya", "Morocco"],
  },
];

export default countries;
